apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warden
resources:
  - namespace.yaml
  - ../k8s.yaml
  - ingress.yaml
patches:
  - target:
      kind: ConfigMap
      name: warden-config
    patch: |-
      - op: replace
        path: /data/WARDEN_PUBLIC_URL
        value: https://warden.vouchins.com
