apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warden
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml
  - ingress.yaml
