(() => {
  "use strict";
  const $ = (s) => document.querySelector(s), principal = () => $("#principal").value.trim();
  const token = async () => $("#access-token").value.trim() || null;
  const headers = async () => { const value = await token(); return value ? {Authorization: `Bearer ${value}`} : {}; };
  const api = async (path, options = {}) => { const response = await fetch(path, {...options, headers: {...await headers(), "Content-Type": "application/json"}}); const body = await response.json(); if (!response.ok) throw new Error(body.detail || `HTTP ${response.status}`); return body; };
  const cell = (value) => { const node = document.createElement("td"); node.textContent = value ?? ""; return node; };
  const action = (label, handler, danger = false) => { const button = document.createElement("button"); button.textContent = label; if (danger) button.className = "danger"; button.onclick = handler; return button; };
  const load = async () => { const suffix = `?principal_id=${encodeURIComponent(principal())}`; const [connections, grants] = await Promise.all([api(`/me/connections${suffix}`), api(`/me/grants${suffix}`)]); const connectionBody = $("#connections"); connectionBody.replaceChildren(...connections.map((item) => { const row = document.createElement("tr"); row.append(cell(item.provider_id), cell(item.account_identifier), cell(item.credential_kind), cell(item.status)); const controls = document.createElement("td"); controls.append(action("Revoke", async () => { await api(`/me/connections/${encodeURIComponent(item.connection_id)}/revoke${suffix}`, {method: "POST", body: JSON.stringify({reason: "Revoked from connection wallet"})}); await load(); }, true)); row.append(controls); return row; })); const grantBody = $("#grants"); grantBody.replaceChildren(...grants.map((item) => { const row = document.createElement("tr"); row.append(cell(item.grant_id), cell(`${item.principal_type}:${item.principal_id}`), cell(item.scopes.join(", ")), cell(`${item.allowed_methods.join(",") || "any"} ${item.path_patterns.join(",")}`), cell(item.status)); const controls = document.createElement("td"); controls.append(action("Revoke", async () => { await api(`/me/grants/${encodeURIComponent(item.grant_id)}/revoke${suffix}`, {method: "POST", body: JSON.stringify({reason: "Revoked from connection wallet"})}); await load(); }, true)); row.append(controls); return row; })); $("#summary").textContent = JSON.stringify({active_connections: connections.filter((item) => item.status === "active").length, active_grants: grants.filter((item) => item.status === "active").length}, null, 2); };
  const connect = $("#connect"); $("#load-connect").onclick = () => { connect.setAttribute("session-token", $("#connect-session").value.trim()); connect.load().catch((error) => alert(error.message)); }; connect.addEventListener("warden-event", (event) => { if (event.detail.type === "success") load().catch(() => {}); }); $("#load").onclick = () => load().catch((error) => alert(error.message)); if (["127.0.0.1", "localhost"].includes(location.hostname)) $("#auth-mode").value = "local"; load().catch(() => {});
})();
